### ISSUE TITLE
装上该脚本机器莫名失联

### ISSUE THREAD

**Issue by AndersonGhost** [YG-tsj/EUserv-warp#11]
在AZ、AWS机器上装上该脚本，使机器获取IPV6，不知为啥CPU占有率变成了100%，第二天就莫名失联了，不知何故。

**Comment by AndersonGhost** [comment]
不知道是不是哪个步骤搞错了

**Comment by YG-tsj** [comment]
用这个
https://github.com/YG-tsj/CFWarp-Pro

**Comment by AndersonGhost** [comment]
难怪的(ಥ_ಥ)   AWS的机器没有了(ಥ﹏ಥ)

**Comment by YG-tsj** [comment]
> 难怪的(ಥ_ಥ) AWS的机器没有了(ಥ﹏ಥ)

你是kvm架构的，原先用错脚本了

**Comment by AndersonGhost** [comment]
是的，找到原因了   谢谢大佬~~
