### ISSUE TITLE
连都连不上，有什么好的办法吗？易操作的

### ISSUE THREAD

**Issue by haobingh** [YG-tsj/EUserv-warp#13]
# **试了**
#   1.嘿呦终端
#   2.he.net的隧道（不会搞）
#   3.还在网上找了个gate one http://ssh.8wf.net:61670/
#   4.手机热点

#   而且套cf总是521

#   可不可以直接用github action 搞定？？

**Comment by YG-tsj** [comment]
https://www.youtube.com/channel/UCxukdnZiXnTFvjF5B5dvJ5w
新频道首发这方面的操作。。
