### ISSUE TITLE
安装成功了 请问如何配置WireGuard呢

### ISSUE THREAD

**Issue by pzb568** [YG-tsj/EUserv-warp#15]
![Screenshot_20210714-052142](https://user-images.githubusercontent.com/38772754/125526893-1fb55863-459d-4f3c-bc70-9bdb04023b12.jpg)
你好 请问这样安装成功了吗

**Comment by YG-tsj** [comment]
这样就好 不用设置了

**Comment by pzb568** [comment]
你好 请问我如何在WireGuard中配置及使用呢

**Comment by pzb568** [comment]
> 这样就好 不用设置了

你好 请问我如何在WireGuard中配置及使用呢

**Comment by YG-tsj** [comment]
直接安装相关代理协议就可以了
