### ISSUE TITLE
install unsuccessfull openvz 7

### ISSUE THREAD

**Issue by malikshi** [YG-tsj/EUserv-warp#18]
here the detail of my vps
 VPS相关信息如下：
------------------------------------------
 操作系统名称 - Ubuntu 20.04.2 LTS
 系统内核版本 - 3.10.0
 CPU架构名称  - x86_64
 虚拟架构类型 - openvz
 -----------------------------------------------
 虚拟架构类型 -  openvz
 对此vps架构不支持，脚本安装自动退出，赶紧提醒甬哥加上你的架构吧！

**Comment by YG-tsj** [comment]
support ipv6 only

**Comment by malikshi** [comment]
Changes to boringtun and works @YG-tsj
