### ISSUE TITLE
EUserv续期日志问题

### ISSUE THREAD

**Issue by liuckv** [YG-tsj/EUserv-warp#20]
EUserv续期日志
正在续费第 1 个账号

第 1 个账号登陆失败，请检查登录信息
这个应该是要收pin码吧？这个能怎么解决

**Comment by YG-tsj** [comment]
账号密码有没输错？多账号之间要有空格

**Comment by liuckv** [comment]
没啊，用户名邮箱能收到pin码？是不是可以设置异地登录不用收pin码的？

**Comment by liuckv** [comment]
另外，想请教下，你的这个续期的话，tg可以接收到信息，但是配置机器人的话，总是不能上线，请问，可以怎么设置

**Comment by YG-tsj** [comment]
不收PIN码，填密码的。。

**Comment by YG-tsj** [comment]
机器人不能上线什么意思？

**Comment by liuckv** [comment]
我知道不收pin码，但是异地ip登录就会被系统阻止登录，要到邮箱收pin码，填了，才能登录的……

**Comment by liuckv** [comment]
在撸的一个项目，系统里面做了tg bot的功能，但是怎么设置，机器人也启动不了，配置里面有socket5  的选项，到不会设置，你的warp能搭个s5的吗？
