### ISSUE TITLE
WARP分配不到ip

### ISSUE THREAD

**Issue by ADDGM** [YG-tsj/EUserv-warp#23]
不知道为什么，始终分配不到WARP的IPV4，各个时间段都尝试了十几次，试了一周了。

**Comment by YG-tsj** [comment]
脚本自带自动反复申请功能，应该可以申请到的。。

**Comment by ADDGM** [comment]
![屏幕截图 2021-08-21 073644](https://user-images.githubusercontent.com/87590261/130302815-d1c72e39-4a22-4311-b196-73c55c4189c9.png)
显示IPV4地址 始终为空，不知道怎么回事

**Comment by YG-tsj** [comment]
重装下系统吧！纯净系统下安装

**Comment by ADDGM** [comment]
成功了！多谢大佬的指导。
原来重装系统就能成功，都折腾我半个月了。
