### ISSUE TITLE
全程按照提示操作，但是在复制配置文件wgcf-account.toml、wgcf.conf时报错。

### ISSUE THREAD

**Issue by lonuslan** [YG-tsj/EUserv-warp#6]
cp: cannot create regular file '/etc/wireguard/wgcf-account.toml': No such file or directory
cp: cannot create regular file '/etc/wireguard/wgcf.conf': No such file or directory

复制时不存在/etc/wireguard/路径，建议在脚本中新增创建 

> mkdir /etc/wireguard

 命令

**Comment by YG-tsj** [comment]
重新安装试试，建议在干净的环境下安装 。。
